Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -2,17 +2,15 @@ name: F3SRP
 
 on:
   schedule:
-    - cron: '*/30 0-23 * * *'
+    - cron: '*/10 0-23 * * *'
 
 jobs:
   runtests:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        attempt: [1, 2, 3]  # Retry up to 3 times
 
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
       - name: Cache Maven dependencies
         uses: actions/cache@v2
@@ -42,13 +40,19 @@ jobs:
           sudo chmod +x /usr/local/bin/chromedriver
 
       - name: Set up Maven
-        run: |
-          sudo apt-get install -y maven
+        run: sudo apt-get install -y maven
 
-      - name: Build with Maven
+      - name: Retry loop
+        id: retry
         run: |
-          mvn test
-
-      - name: Check if it failed
-        if: ${{ failure() && matrix.attempt != 3 }}  # Retry if not the final attempt
-        run: exit 1  # Trigger retry if it failed
+          for i in {1..3}; do
+            echo "Attempt $i"
+            mvn test && break
+            if [ $i -lt 3 ]; then
+              echo "Test failed. Retrying..."
+              sleep 10  # Wait for 10 seconds before retrying
+            else
+              echo "Test failed after $i attempts."
+              exit 1
+            fi
+          done
